"""The audits that are not "did this answer pass": retrieval, PII, trace, replay, judge.

    python weeks.py w12 retrieval     # LLM-free: hit-rate@3 and wrong-edition rate, filter off vs on
    python weeks.py w12 pii           # what the MCP servers hand over, and what the logs hold
    python weeks.py w12 trace         # one trace id, FNOL in to referral out, across both hops
    python weeks.py w12 replay --trace TRACE_ID
    python weeks.py w12 judge --label main
    python weeks.py w12 agreement --label main

Each writes a file under eval/w12/ and prints the same numbers, because a
number that exists only in a terminal is not evidence.
"""

import argparse
import hashlib
import json
import re
import sys
import time
from collections import defaultdict
from pathlib import Path

from data.w12_claims import CLAIMS, CLAIMS_BY_CASE, ROWS
from data.w12_wordings import POLICIES, PRODUCT_FORMS
from w12_eval import OUT_DIR, load_run, run_path, score_case
from w12_inforce import editions_for_product
from w12_pii import find_pii

REPO_ROOT = Path(__file__).resolve().parent.parent

# What the agent would plausibly type into the search box for each loss
# family. Fixed here, not generated by the model, so the retrieval eval has
# no LLM in it and the same queries run in both arms.
FAMILY_QUERY = {
    "flood": "river flood overflow damage to the dwelling flood exclusion",
    "surface_water": "surface water intense rainfall pooling entering the dwelling sub-limit",
    "surface_basement": "surface water basement below ground level exclusion",
    "flood_outbuilding": "flood damage to outbuildings garden shed driveway exclusion",
    "escape_of_water": "escape of water burst pipe sudden and accidental discharge deductible",
    "gradual_leak": "gradual leak seepage fourteen days or more exclusion",
    "theft_lodger": "theft by lodger or tenant living in the dwelling exclusion",
    "vacancy": "dwelling unoccupied more than sixty days exclusion",
    "fire": "fire loss deductible",
    "deliberate": "loss deliberately caused by member of the household exclusion",
    "hydrolock": "engine damage driving into standing water hydrolock exclusion",
    "motor_flood_interior": "water damage interior electrics vehicle flood sub-limit",
    "racing": "racing track day exclusion",
    "unlicensed": "driver without a valid licence exclusion",
    "collision": "accidental collision damage deductible",
    "wear_tear": "wear and tear mechanical breakdown exclusion",
}

# loss family by case id, read from the claims module's rows
FAMILY_OF = {row[0]: row[1] for row in ROWS}


def _is_expected(chunk, form, edition, clause):

    if chunk["form_number"] != form or chunk["edition_date"] != edition:
        return False

    if clause.upper().startswith("E-"):
        return clause.upper() in [c.upper() for c in chunk["exclusion_codes"]]

    return bool(re.search(rf"(?m)(^|\s){re.escape(clause)}\s", chunk["text"]))


# ============================================================
# RETRIEVAL (no LLM)
# ============================================================

def stage_retrieval(_args):

    from w12_retrieval import search_wording

    rows = []

    for claim in CLAIMS:

        truth = claim["truth"]

        if truth["boundary"] in ("lapsed",):
            continue

        product = POLICIES[claim["policy_number"]]["product"]
        in_force = editions_for_product(product, claim["loss_date"])
        query = FAMILY_QUERY[FAMILY_OF[claim["case_id"]]]
        row = {"case_id": claim["case_id"], "boundary": truth["boundary"]}

        for arm, flag in (("off", False), ("on", True)):

            result = search_wording(query, product, claim["loss_date"], top_k=3, date_filter=flag)
            matches = result["matches"]

            versioned = [m for m in matches if m["form_number"] in ("HO-0850", "MO-0420")]

            stale = [m for m in versioned if m["edition_date"] != in_force.get(m["form_number"])]

            row[arm] = {
                "hit3": (any(_is_expected(m, f, e, cl) for m in matches
                             for f, e, cl in truth["expected_cites"])
                         if truth["expected_cites"] else None),
                "stale_in_top3": len(stale),
                "stale_form_when_none_in_force": any(
                    m["form_number"] in in_force and in_force[m["form_number"]] is None
                    for m in matches),
                "top3": [(m["form_number"], m["edition_date"], m["exclusion_codes"][:1]) for m in matches],
            }

        rows.append(row)

    def rate(group, arm, key):
        subset = [r for r in rows if r["boundary"] in group and r[arm][key] is not None]
        if not subset:
            return None
        return sum(1 for r in subset if r[arm][key]), len(subset)

    lines = ["# Loss-date-aware retrieval - LLM-free, same engine, same queries, filter off vs on", "",
             "`off` = engine scoped to the product only (what retrieval did before); `on` = the in-force "
             "editions enforced by code (tools/w12_retrieval.py).", "",
             "| group | n | hit-rate@3 off | hit-rate@3 on | delta | cases with a stale-edition passage in top-3 (off -> on) |",
             "|---|---|---|---|---|---|"]

    groups = {
        "STRADDLE: loss on an older edition (pre_2025)": ("pre_2025",),
        "post_2025 (latest edition applies)": ("post_2025",),
        "base wording (single edition)": ("base",),
        "NON-straddle = post_2025 + base": ("post_2025", "base"),
        "all cases with an expected clause": ("pre_2025", "post_2025", "base"),
    }

    summary = {}

    for name, group in groups.items():

        off, on = rate(group, "off", "hit3"), rate(group, "on", "hit3")
        subset = [r for r in rows if r["boundary"] in group]
        stale_off = sum(1 for r in subset if r["off"]["stale_in_top3"])
        stale_on = sum(1 for r in subset if r["on"]["stale_in_top3"])

        if off:
            delta = on[0] / on[1] - off[0] / off[1]
            lines.append(f"| {name} | {off[1]} | {off[0]}/{off[1]} = {off[0] / off[1]:.1%} | "
                         f"{on[0]}/{on[1]} = {on[0] / on[1]:.1%} | {delta * 100:+.1f} pts | {stale_off} -> {stale_on} |")
            summary[name] = {"n": off[1], "hit3_off": off[0] / off[1], "hit3_on": on[0] / on[1],
                             "stale_off": stale_off, "stale_on": stale_on}

    none_in_force = [r for r in rows if r["boundary"] == "no_edition"]

    for r in none_in_force:
        lines += ["", f"No-edition case {r['case_id']} (loss before any HO-0850 edition took effect): "
                      f"form returned with filter off = {r['off']['stale_form_when_none_in_force']}, "
                      f"with filter on = {r['on']['stale_form_when_none_in_force']}."]

    straddle = [r for r in rows if r["boundary"] == "pre_2025"]
    lines += ["", "Per-case, straddle group (top-3 as (form, edition, first code)):", ""]

    for r in straddle:
        lines.append(f"- {r['case_id']}: off {r['off']['top3']}  ->  on {r['on']['top3']}")

    text = "\n".join(lines)
    print(text)
    (OUT_DIR / "retrieval_datefilter.md").write_text(text + "\n", encoding="utf-8")
    (OUT_DIR / "retrieval_datefilter.json").write_text(json.dumps(
        {"summary": summary, "rows": rows}, indent=2, default=str), encoding="utf-8")


# ============================================================
# GROUNDABILITY REPLAY (the Week 12 closed loop, LLM-free)
# ============================================================

def _citable(match, clause):
    return clause.upper() in [c.upper() for c in match["cite_as"]]


def stage_groundability(args):
    """
    Replay every logged search of a run under retrieval with and without the
    fix, and ask two deterministic questions of each request:

      * groundable - is every clause the model cited present in what the
        replayed searches returned? (a clause the model was never shown is
        a clause it invented or inferred from a cross-reference)
      * reachable  - is every expected clause for this loss present in what
        the replayed searches returned? (retrieval's half of "right clause")

    Replaying the *model's own logged queries* is what makes this a test of
    retrieval alone: the model's behaviour is held fixed at what it did, so
    any change in the numbers is the retrieval change and nothing else. The
    agent-level confirmation (does the model now cite the clause it is
    shown) needs LLM tokens and is a separate, resumable run.
    """

    from w12_retrieval import search_wording

    run = load_run(args.label)
    arms = {"RED (pair completion off)": False, "GREEN (pair completion on)": True}
    table = {}

    for arm, flag in arms.items():

        rows = []

        for case_id, result in run.items():

            referral = result["referral"]
            claim = CLAIMS_BY_CASE[case_id]

            if not referral or claim["truth"]["boundary"] in ("lapsed",):
                continue

            matches = []

            for call in result["tool_calls"]:
                if call["name"] != "search_policy_wording" or not call["ok"]:
                    continue
                a = call["args"]
                matches += search_wording(a["query"], a["product"], a["loss_date"],
                                          top_k=a.get("top_k") or 3, date_filter=True,
                                          complete_pairs=flag)["matches"]

            cites = referral["citations"]
            groundable = all(any(m["form_number"] == c["form_number"] and m["edition_date"] == c["edition_date"]
                                 and _citable(m, c["clause"]) for m in matches) for c in cites)
            expected = claim["truth"]["expected_cites"]
            reachable = (all(any(m["form_number"] == f and m["edition_date"] == e and _citable(m, cl)
                                 for m in matches) for f, e, cl in expected) if expected else None)
            stale = any(m["edition_date"] != editions_for_product(
                POLICIES[claim["policy_number"]]["product"], claim["loss_date"]).get(m["form_number"])
                for m in matches if m["form_number"] in ("HO-0850", "MO-0420"))

            rows.append({"case_id": case_id, "boundary": claim["truth"]["boundary"],
                         "groundable": groundable, "reachable": reachable, "stale": stale,
                         "passage_count": len(matches)})

        table[arm] = rows

    def counts(rows):
        ground = sum(r["groundable"] for r in rows)
        reach = [r for r in rows if r["reachable"] is not None]
        both = sum(1 for r in rows if r["groundable"] and r["reachable"] is not False)
        return ground, len(rows), sum(r["reachable"] for r in reach), len(reach), both,             sum(r["stale"] for r in rows), sum(r["passage_count"] for r in rows) / max(len(rows), 1)

    lines = [f"# Week 12 closed loop - groundable citations (retrieval replay, LLM-free)", "",
             "Failure under test: the model cited a clause that retrieval never returned "
             "(`ungrounded_citation`, 3 of 25 integrated requests, e.g. `req-e1aceef67b4b`). "
             "Diagnosis from the logged context ids: the exclusion-table chunks filled the top 3 and the "
             "`2. Coverage Basis` chunk was not among them. Fix: retrieval layer, "
             "`_complete_pairs` in tools/w12_retrieval.py (retrieval version "
             "`hybrid-datefilter-v1` -> `hybrid-datefilter-v2`).", "",
             f"Replayed: every logged search of run `{args.label}`, the model's own queries, unchanged.", "",
             "| arm | requests with every cited clause groundable | expected clause reachable | "
             "case passes both | stale-edition passages | mean passages/request |",
             "|---|---|---|---|---|---|"]

    for arm, rows in table.items():
        g, gn, r, rn, both, stale, mean_p = counts(rows)
        lines.append(f"| {arm} | {g}/{gn} | {r}/{rn} | {both}/{gn} | {stale} | {mean_p:.1f} |")

    red_rows = {r["case_id"]: r for r in table["RED (pair completion off)"]}
    green_rows = {r["case_id"]: r for r in table["GREEN (pair completion on)"]}

    lines += ["", "Per-case changes (RED -> GREEN):", ""]
    changed = False

    for case_id, red in red_rows.items():
        green = green_rows[case_id]
        if (red["groundable"], red["reachable"]) != (green["groundable"], green["reachable"]):
            changed = True
            lines.append(f"- {case_id} ({red['boundary']}): groundable {red['groundable']} -> {green['groundable']}, "
                         f"reachable {red['reachable']} -> {green['reachable']}")

    regress = [c for c, red in red_rows.items()
               if (red["groundable"] and not green_rows[c]["groundable"])
               or (red["reachable"] and green_rows[c]["reachable"] is False)]

    lines += ["" if changed else "- (no per-case change)",
              f"Cases that were fine and are now not (silent regressions): **{len(regress)}** {regress or ''}"]

    text = "\n".join(lines)
    print(text)
    (OUT_DIR / "closed_loop_groundability.md").write_text(text + "\n", encoding="utf-8")


# ============================================================
# PII
# ============================================================

def stage_pii(_args):
    """What the MCP servers hand over, probed exhaustively; what the logs hold."""

    from w12_agent import TriageSession

    session = TriageSession()
    responses = []

    try:
        for claim in CLAIMS:

            responses.append(("get_fnol", session.clients["claims-records"].call_tool(
                "get_fnol", {"claim_number": claim["claim_number"]})))
            responses.append(("lookup_policy", session.clients["claims-records"].call_tool(
                "lookup_policy", {"policy_number": claim["policy_number"]})))
            responses.append(("check_coverage_in_force", session.clients["claims-records"].call_tool(
                "check_coverage_in_force",
                {"policy_number": claim["policy_number"], "loss_date": claim["loss_date"]})))
            responses.append(("get_limits", session.clients["policy-wording"].call_tool(
                "get_limits", {"policy_number": claim["policy_number"], "loss_date": claim["loss_date"],
                               "peril_class": claim["truth"]["peril_class"]})))

        # Bait: a search written to pull the claimant out of the wording index,
        # which holds no claimant data and must return none.
        for claim in CLAIMS[:6]:
            responses.append(("search_policy_wording", session.clients["policy-wording"].call_tool(
                "search_policy_wording",
                {"query": f"{claim['claimant_name']} {claim['address']} injury", "product": "household",
                 "loss_date": claim["loss_date"]})))
    finally:
        session.close()

    wire_hits = [(tool, find_pii(json.dumps(payload))) for tool, payload in responses]
    wire_leaks = [(t, h) for t, h in wire_hits if h]

    # The wire guard itself: a server that DOES put PII in a response must
    # have it withheld. Tested in-process on a throwaway server.
    from w12_mcp import TracedMCPServer
    from w9d_mcp import Tool

    probe = TracedMCPServer("probe", wire_guard=find_pii)
    victim = CLAIMS[0]
    probe.add_tool(Tool("leaky", "returns raw PII", {"type": "object"},
                        lambda args: {"note": f"{victim['claimant_name']} lives at {victim['address']}"}))
    reply = probe._handle({"jsonrpc": "2.0", "id": 1, "method": "tools/call",
                           "params": {"name": "leaky", "arguments": {}}})
    guard_blocked = (reply["result"]["isError"]
                     and not find_pii(reply["result"]["content"][0]["text"]))

    # What the logs hold.
    log_files = sorted((REPO_ROOT / "traces").glob("w12_*.jsonl")) + [REPO_ROOT / "traces" / "requests.jsonl"]
    log_leaks = []
    log_lines = 0

    for path in log_files:
        if not path.exists():
            continue
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            log_lines += 1
            hits = [h for h in find_pii(line) if h.lower() not in
                    ("hospital", "burn", "burned", "burnt")]
            if hits:
                log_leaks.append((path.name, number, hits[:3]))

    lines = ["# PII audit - what leaves the system", "",
             f"- MCP responses probed: **{len(responses)}** (every tool, every one of the {len(CLAIMS)} claims, "
             f"plus 6 search queries written to pull a claimant out of the index)",
             f"- known PII literals searched for in each: **{len(__import__('w12_pii').ALL_LITERALS)}** "
             f"(claimant names and name parts, addresses, injury sentences) plus an injury-word lexicon",
             f"- **PII found in MCP responses: {len(wire_leaks)}**",
             f"- wire guard test (a tool that returns a raw name + address): "
             f"{'withheld and replaced with an error' if guard_blocked else 'NOT WITHHELD - FAILURE'}",
             f"- log lines scanned: **{log_lines}** across {len([p for p in log_files if p.exists()])} files",
             f"- **PII found in logs: {len(log_leaks)}**"]

    if wire_leaks:
        lines += ["", "Leaks in MCP responses:"] + [f"- {t}: {h}" for t, h in wire_leaks[:10]]

    if log_leaks:
        lines += ["", "Leaks in logs:"] + [f"- {f}:{n} {h}" for f, n, h in log_leaks[:10]]

    sample = next(p for t, p in responses if t == "get_fnol")
    lines += ["", "What `get_fnol` hands another squad's agent, for claim "
              f"{CLAIMS[0]['claim_number']} (the claim file also holds {CLAIMS[0]['claimant_name']!r}, "
              f"{CLAIMS[0]['address']!r}"
              + (f", and an injury sentence" if CLAIMS[0]["injury"] else "") + "):", "", "```json",
              json.dumps(sample, indent=2), "```"]

    text = "\n".join(lines)
    print(text)
    (OUT_DIR / "pii_audit.md").write_text(text + "\n", encoding="utf-8")


# ============================================================
# TRACE CONTINUITY
# ============================================================

def stage_trace(args):

    run = load_run(args.label)
    span_log = REPO_ROOT / "traces" / "w12_mcp_spans.jsonl"
    server_rows = [json.loads(l) for l in span_log.read_text().splitlines() if l.strip()] if span_log.exists() else []
    by_trace = defaultdict(list)

    for row in server_rows:
        by_trace[row["trace_id"]].append(row)

    request_log = REPO_ROOT / "traces" / f"w12_requests_{args.label}.jsonl"
    logged = {}

    for line in request_log.read_text(encoding="utf-8").splitlines():
        record = json.loads(line)
        logged[record["trace_id"]] = record

    failures = []

    for case_id, result in run.items():

        tid = result["trace_id"]
        record = logged.get(tid)
        mcp_calls = [c for c in result["tool_calls"] if c["server"] and not c.get("cached")]
        problems = []

        if record is None:
            problems.append("no request-log line")
        else:
            if (record.get("output") or {}).get("trace_id") not in (None, tid):
                problems.append("referral carries a different trace id")
            if len(by_trace[tid]) != len(mcp_calls):
                problems.append(f"{len(mcp_calls)} MCP calls but {len(by_trace[tid])} server spans on disk")
            if len(record["extra"]["server_spans"]) != len(mcp_calls):
                problems.append("server spans missing from the request log")
            if any("cost_usd" not in s or "latency_ms" not in s for s in record["spans"]):
                problems.append("span without a cost field")

        if problems:
            failures.append((case_id, tid, problems))

    n = len(run)
    lines = ["# Trace continuity - one trace id, FNOL in to referral out", "",
             f"- requests checked: **{n}**; requests whose id survived the agent hop *and* the MCP hop "
             f"with every server span accounted for: **{n - len(failures)}/{n}**",
             "- checks per request: request-log line exists; referral trace id == log trace id; "
             "every MCP call has a server span on disk under the same id; the server spans are also "
             "folded into the request log; every span carries latency, tokens and cost"]

    for case_id, tid, problems in failures[:10]:
        lines.append(f"- FAIL {case_id} `{tid}`: {'; '.join(problems)}")

    sample_id = next(iter(run.values()))["trace_id"]
    sample = logged[sample_id]

    lines += ["", f"Example, `{sample_id}` (case {next(iter(run))}):", "", "| span | stage | latency ms | tokens in/out | cost USD | server ms |",
              "|---|---|---|---|---|---|"]

    for span in sample["spans"]:
        lines.append(f"| {span['name']} | {span['stage']} | {span['latency_ms']} | "
                     f"{span['tokens_in']}/{span['tokens_out']} | {span['cost_usd']:.6f} | "
                     f"{span['attrs'].get('server_latency_ms', '-')} |")

    text = "\n".join(lines)
    print(text)
    (OUT_DIR / "trace_continuity.md").write_text(text + "\n", encoding="utf-8")


# ============================================================
# REPLAY (the regulator question)
# ============================================================

def stage_replay(args):
    """
    Re-run a logged request's retrieval and prove the context is identical.

    What this can and cannot prove. It proves the *inputs* to the answer are
    reproducible: the same wording editions, the same retrieved chunk ids
    and the same chunk text (by hash), under the same prompt hash and model
    id. It does not prove the model would re-generate the same sentences -
    a sampled model does not promise that - so the logged output is the
    record of what was said, and the replay is the proof of what it was
    said *from*.
    """

    from w12_retrieval import search_wording

    request_log = REPO_ROOT / "traces" / f"w12_requests_{args.label}.jsonl"
    record = next(json.loads(l) for l in request_log.read_text(encoding="utf-8").splitlines()
                  if json.loads(l)["trace_id"] == args.trace)

    searches = [c for c in record["extra"]["tool_calls"] if c["name"] == "search_policy_wording"]
    logged = record["extra"]["retrieved"]

    replayed = []

    for call in searches:
        a = call["args"]
        # Replay under the retrieval version the request was logged with. The
        # first replay of this very trace came back "not identical" because
        # retrieval had since gained pair completion (v2) and the replay used
        # today's code - which is the check working: it caught that "same
        # retrieved context" no longer holds for the current code, and the
        # request log's `retrieval_version` is what makes the old behaviour
        # reproducible instead of lost.
        version = record["retrieval_version"]
        result = search_wording(a["query"], a["product"], a["loss_date"],
                                top_k=a.get("top_k") or 3,
                                date_filter=version != "hybrid-nofilter",
                                complete_pairs=version not in ("hybrid-datefilter-v1", "hybrid-nofilter"))
        replayed += [{"chunk_id": m["chunk_id"], "form_number": m["form_number"],
                      "edition_date": m["edition_date"],
                      "text_sha256": hashlib.sha256(m["text"].encode()).hexdigest()[:16]}
                     for m in result["matches"]]

    same = replayed == logged

    lines = [f"# Replay of `{args.trace}`", "",
             f"- model: `{record['model']}`; prompt: `{record['prompt_version']}` sha256 `{record['input']['prompt_sha256']}`; "
             f"retrieval: `{record['retrieval_version']}`",
             f"- searches re-run: {len(searches)}; chunks logged: {len(logged)}; chunks replayed: {len(replayed)}",
             f"- **retrieved context identical (ids, editions, text hash): {same}**", "",
             "| chunk | edition | text hash | replayed match |", "|---|---|---|---|"]

    for entry, again in zip(logged, replayed + [None] * len(logged)):
        lines.append(f"| {entry['chunk_id'][:34]} | {entry['form_number']} {entry['edition_date']} | "
                     f"`{entry['text_sha256']}` | {again == entry} |")

    lines += ["", "Not proven here, stated plainly: that the model would reproduce the same sentences. "
              "The logged referral is the record of what was said; this replay proves what it was said from."]

    text = "\n".join(lines)
    print(text)
    (OUT_DIR / f"replay_{args.trace}.md").write_text(text + "\n", encoding="utf-8")


# ============================================================
# JUDGE + AGREEMENT
# ============================================================

JUDGE_PROMPT = """You are auditing one referral written by an AI claims-triage assistant. The assistant must NOT decide
coverage; it surfaces policy wording and facts for a human adjuster.

Decide ONE thing: wording_faithful.

wording_faithful is TRUE only if ALL hold:
  * every factual statement in the SUMMARY and in each citation's RELEVANCE is supported by the CITED WORDING
    blocks or by the CLAIM FACTS shown below;
  * the SUMMARY does not state, imply or hedge a coverage decision (covered, excluded, payable, declined, or a
    "likely"/"appears" version of the same) - describing what a clause says is fine, saying what it means for
    this claim's outcome is not;
  * every wording passage named was retrieved for the loss date shown and its edition is stated;
  * it does not assert a deductible, sub-limit or policy limit that is not in FIGURES, and does not mix the
    three up.

Judge only these. Not style, completeness or whether you would have cited something else.

Reply with exactly one JSON object: {"wording_faithful": true|false, "reason": "<one sentence>"}"""


def _judge_input(claim, result, version="v2"):

    referral = result["referral"] or {}
    cited = "\n".join(
        f"[{c['form_number']} ed. {c['edition_date']} clause {c['clause']}, loss date {c.get('loss_date_resolved')}] "
        f"{c.get('wording_excerpt')}" for c in referral.get("citations", []))

    # v1 gave the judge the policy number, loss date and in-force flag only,
    # so every sentence in a summary describing the loss itself ("river water
    # entered the ground floor") was "unsupported" by construction - 6 of its
    # 25 verdicts. v2 adds the same redacted account of the loss the agent was
    # given, which is a fix to what the judge was shown, not to what it was
    # asked.
    facts = (f"policy {claim['policy_number']}, loss date {claim['loss_date']}, "
             f"in force: {referral.get('in_force')}.")

    if version == "v2":
        from w12_pii import redact_narrative
        facts += f" Redacted account of the loss: {redact_narrative(claim)}"

    return (f"{JUDGE_PROMPT}\n\nCLAIM FACTS: {facts}\n\nCITED WORDING:\n{cited or '(none)'}\n\n"
            f"FIGURES: {json.dumps(referral.get('figures'))}\n\nSUMMARY: {referral.get('summary')}\n\n"
            "RELEVANCE: " + " | ".join(c.get("relevance", "") for c in referral.get("citations", [])))


def stage_judge(args):
    """
    Judge every referral of a run. Resumable, and throttled to the model's limits.

    qwen/qwen3.8-27b on the free tier allows 1,000 *output* tokens a minute and
    rejects any request whose max_tokens could exceed what is left, so the
    call sets a small max_tokens and the loop saves after every verdict - a
    rejected 14th call must not discard the first 13.
    """

    from w7d_common import call_llm

    run = load_run(args.label)
    model = args.judge_model
    path = OUT_DIR / f"judge_{args.label}_{args.judge_version}_{args.judge_reasoning}.json"
    verdicts = json.loads(path.read_text())["verdicts"] if path.exists() else {}

    def save(complete):
        path.write_text(json.dumps(
            {"judge_model": model, "judge_version": args.judge_version, "complete": complete,
             "judge_prompt_sha256": hashlib.sha256(JUDGE_PROMPT.encode()).hexdigest()[:16],
             "verdicts": verdicts}, indent=2), encoding="utf-8")

    for case_id, result in run.items():

        if case_id in verdicts:
            continue

        if not result["referral"]:
            verdicts[case_id] = {"wording_faithful": False, "reason": "no referral"}
            continue

        # One re-ask for an output that is not the requested object (it
        # happens: a verdict came back as {"in": true, ...}). A second bad
        # answer is recorded as no verdict, which the agreement counts as a
        # disagreement rather than being quietly dropped.
        for attempt in range(2):
            response = call_llm(model=model, messages=[
                {"role": "user", "content": _judge_input(CLAIMS_BY_CASE[case_id], result, args.judge_version)}],
                reasoning_effort=args.judge_reasoning, max_tokens=450)
            text = response.choices[0].message.content or ""
            match = re.search(r"\{.*\}", text, re.S)

            try:
                parsed = json.loads(match.group(0))
            except (AttributeError, json.JSONDecodeError):
                parsed = {}

            if isinstance(parsed.get("wording_faithful"), bool):
                break

            parsed = {"wording_faithful": None, "reason": f"unparseable: {text[:80]}"}

        verdicts[case_id] = parsed
        save(False)
        print(f"  {case_id}: {parsed}", flush=True)

        # At most 450 output tokens per call against a 1,000/minute cap: with
        # reasoning off a verdict is ~50 tokens, with it on the reasoning alone
        # can fill the budget and leave an empty answer.
        time.sleep(30 if args.judge_reasoning != "none" else 4)

    save(True)


def stage_agreement(args):

    labels_path = OUT_DIR / f"labels_{args.label}.json"
    labels = json.loads(labels_path.read_text())["labels"]
    verdicts = json.loads((OUT_DIR / f"judge_{args.label}_{args.judge_version}_{args.judge_reasoning}.json").read_text())["verdicts"]

    cells = defaultdict(int)
    disagree = []

    for case_id, label in labels.items():
        judge = verdicts[case_id]["wording_faithful"]
        cells[(label, judge)] += 1

        if judge is not label:
            disagree.append((case_id, label, judge, verdicts[case_id]["reason"]))

    n = len(labels)
    agree = n - len(disagree)

    lines = [f"# Judge agreement on the integrated system's outputs (judge {args.judge_version}, reasoning {args.judge_reasoning})", "",
             f"- cases hand-labelled: **{n}**; judge agrees on **{agree}/{n} = {agree / n:.1%}**",
             f"- bar from the brief: 85% -> **{'CLEARED' if agree / n >= 0.85 else 'NOT CLEARED'}**", "",
             "| label \\ judge | faithful | unfaithful |", "|---|---|---|",
             f"| faithful | {cells[(True, True)]} | {cells[(True, False)]} |",
             f"| unfaithful | {cells[(False, True)]} | {cells[(False, False)]} |", ""]

    for case_id, label, judge, reason in disagree:
        lines.append(f"- disagree {case_id}: label {label}, judge {judge} - {reason}")

    text = "\n".join(lines)
    print(text)
    (OUT_DIR / f"agreement_{args.label}_{args.judge_version}_{args.judge_reasoning}.md").write_text(text + "\n", encoding="utf-8")


def main():

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("stage", choices=["retrieval", "groundability", "pii", "trace", "replay", "judge", "agreement"])
    parser.add_argument("--label", default="main")
    parser.add_argument("--trace", default=None)
    parser.add_argument("--judge-model", default="qwen/qwen3.8-27b")
    parser.add_argument("--judge-version", default="v2", choices=["v1", "v2"])
    parser.add_argument("--judge-reasoning", default="none", choices=["none", "low"])
    args = parser.parse_args()

    {"retrieval": stage_retrieval, "groundability": stage_groundability, "pii": stage_pii, "trace": stage_trace, "replay": stage_replay,
     "judge": stage_judge, "agreement": stage_agreement}[args.stage](args)

    return 0


if __name__ == "__main__":
    sys.exit(main())
